### PR TITLE
Revert previous change that pinned setuptools to 62.0.0

### PR DESCRIPTION
**Pull request by MarkWieczorek**
As an attempt to get some of the recent PRs to build, it was necessary to pin setuptools to 62.0.0. In the most recent version (62.1.0) the locations of the build directories changed, causing compilation errors. Though using 62.0.0 helped, the PR still failed...

I have fixed the pyshtools `setup.py` file to deal with both the old 62.0.0 and 62.1.0 build directory locations. I will be starting a new release soon (today?), so it is no longer necessary to pin setuptools. We will see what happens then...

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
Probably best to have open ended ranges for the pins in conda forge if possible. Fixed pins or even very narrow range pins make it difficult to install a package alongside other packages.

**Comment by MarkWieczorek** [comment]
I agree, and this got reverted yesterday. I fixed the setup.py of the project to work with both <=62.0.0 and >=62.1.0, but this will only work with pyshtools >=4.10. The old PRs on this repo for v4.9.1 simply wont work now, but that is ok with me since I just put out 4.10 yesterday.
